testing:
  pilotTestFlag: N
  testDate: January 18
  testID:

server:
  port: 8092

blog:
  url: https://georgerrmartin.com/notablog/
  
scheduling:
  time: 4
  
#Here you can configure smtp properties for app mail
spring:
  #mail:
    #host: smtp.gmail.com
    #port: 587
    #username:
    #password:
    #properties:
      #mail:
        #smtp:
          #auth: true
          #starttls:
            #enable: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/asoiafalerts?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver

